### ISSUE TITLE
Views 구성

### ISSUE THREAD

**Issue by goohooh** [goohooh/art_archive#4]
- 기본 페이지 라우팅 및 렌더링
 - 기본 static files(css, js) 설정

**Comment by phs1919** [comment]
기본 페이지 라우팅 및 렌더링에서 기본 페이지라고 함은 어떤 라우트를 갖는 페이지인지, 어떤 내용을 구성하는 페이지인지 구체적으로 말씀해주시면 더 도움이 될거 같습니다!

**Comment by goohooh** [comment]
기본페이지 => home.html입니다. 최상위 경로( ' / ' )로 라우팅합니다.
저는 기본페이지에 모든 ajax통신을 위한 버튼을 만들 계획입니다. 상단에 arists와 images각 리소스들의 통신을 위한  버튼들의 구역과, 응답결과를 하단에 렌더링해주는 구조입니다.

**Comment by phs1919** [comment]
네 설명 감사합니다. 슬랙에서 의견을 물어보셨듯이 artists와 images의 리소스들을 위한 통신과 어떤 응답결과를 어떻게 렌더링을 하실지를 알려주시면 더 좋을거 같습니다. 가령, artists의 정보를 가져오기 위하여
`GET /artists` endpoint에 params없이 요청을 하면 200 response일 경우 페이지에 어떻게 랜더링이 되는건지 404가 나올 경우에는 alert 메시지를 보여준다는식으로 조금 더 세분화했으면 바램이었습니다 :)

**Comment by goohooh** [comment]
제 설명이 부족했습니다.

우선 하나의 페이지를 상,하단으로 나눕니다. 상단은 다시 2열로 나뉘어 artists, images에 대한 컨트롤을 하게됩니다. 하단은 결과를 렌더링합니다.

`GET /artists` : 파라미터(id)가 없을경우 리스트를 가져옵니다. 200일경우 하단에는 artist name과 디테일버튼이 리스트로 렌더링됩니다. 아무런 값이 없는 404일 경우 말씀해주신대로 alert창으로 메시지를 띄웁니다.

`GET /artists/<id>` : 이름 옆의 디테일 버튼을 누르면 앞의 endpoint로 통신하여 artist의 디테일 정보를 가지고 옵니다. 정보는 새로운 레이어를 띄웁니다. 새 레이어에는 디테일한 정보값들과 수정/삭제 버튼이 있습니다. 각 버튼은 다시 ajax 통신을 합니다. 수정의 경우 레이어 하단으로 폼을 슬라이드 시켜 입력 받도록 합니다. endpoint는 그대로이며 요청만 PUT, DELETE로 다릅니다.

`GET /artist?` : 검색또한 폼을 슬라이드 시켜 보여줍니다. 통합검색이 아니라 각 폼 필드(name, country, genre 등..)값을 입력 받고, 값이 있는 필드만 전송합니다. 200일경우 리스트를 렌더링하는 것 처럼 결과를 하단에 렌더링 합니다. 폼 입력이 잘못됐을 경우 400과 함께 alert창으로 메시지를 띄웁니다.

`POST /artist/new/` : create artist버튼을 누르면 슬라이드 되는 폼에 필드값들을 입력합니다. ajax통신으로 각 값들을 전송합니다. 201일경우 새로 만들어진 artist의 디테일 레이어가 띄워집니다. 400은 alert창으로 에러메시지를 띄웁니다.

images 리소스들도 같은 프로세스를 가집니다.
