### ISSUE TITLE
artists, images의  API 구현

### ISSUE THREAD

**Issue by goohooh** [goohooh/art_archive#5]
- jQuery를 이용한 ajax 통신 라우팅
 - 데이터 렌더링
 - 에러 처리

**Comment by phs1919** [comment]
제목으로 artists, images의 API 구현으로 말씀해주셔서 대략적인 것은 이해할 수 있는데, 구체적인 내용. 즉, 요청 종류나 parameter의 종류, 데이터는 어떤게 반응이 올거라 기대하고 이에 따라 어떻게 처리할 것인지에 대한 내용이 포함되면 더 좋을거 같아요. 아직 작업중이셔서 제가 너무 일찍 피드백을 드리는거 일 수도 있겠네요 ^^;
